# -*- coding: utf-8 -*-
"""Another copy of Model_Training_SIH2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AreNiyxhZgRTMk6OWWg8V7OtSNil4xDu
"""

# @title
!pip uninstall -y tacoreader -q
!pip install -q "tacoreader<1.0" rasterio matplotlib numpy

from google.colab import drive
drive.mount('/content/drive')

!unzip "/content/drive/MyDrive/something.zip" -d "/content/sen2venus_cache"

!mv /content/sen2venus_cache/content/sen2venus_cache/* /content/sen2venus_cache/
!rm -rf /content/sen2venus_cache/content

# @title
import tacoreader
import rasterio as rio
import matplotlib.pyplot as plt
import numpy as np

print(tacoreader.__version__)

dataset = tacoreader.load("tacofoundation:sen2venus")

print(dataset)

"""### Real Code"""

!pip install -q torch torchvision scipy scikit-image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import numpy as np
import rasterio as rio

# ============================================
# 1. PYTORCH DATASET
# ============================================

class Sen2VenusDataset(Dataset):

    def __init__(self, taco_dataset, indices):
        self.dataset = taco_dataset
        self.indices = indices

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, i):

        idx = self.indices[i]

        row = self.dataset.read(idx)

        lr_path = row.read(0)
        hr_path = row.read(1)

        # Read LR: 10 bands, 128×128
        with rio.open(lr_path) as src:
            lr = src.read().astype(np.float32)

        # Read HR: 8 bands, 256×256
        with rio.open(hr_path) as src:
            hr = src.read().astype(np.float32)

        # Convert uint16 reflectance values
        lr /= 10000.0
        hr /= 10000.0

        # PyTorch tensors: [C,H,W]
        lr = torch.from_numpy(lr)
        hr = torch.from_numpy(hr)

        return lr, hr

# @title
# ============================================
# SELECT 1000 SAMPLES
# ============================================

import numpy as np

rng = np.random.default_rng(42)

train_indices = rng.choice(
    len(dataset),
    size=min(1000, len(dataset)),
    replace=False
)

print("Selected samples:", len(train_indices))

# @title
# ============================================
# 2. CACHE DATASET
# ============================================

import os
import numpy as np
import rasterio as rio

cache_dir = "/content/sen2venus_cache"
os.makedirs(cache_dir, exist_ok=True)

for n, idx in enumerate(train_indices):

    lr_file = f"{cache_dir}/{n}_lr.npy"
    hr_file = f"{cache_dir}/{n}_hr.npy"

    if os.path.exists(lr_file) and os.path.exists(hr_file):
        continue

    row = dataset.read(idx)

    with rio.open(row.read(0)) as src:
        lr = src.read().astype(np.float32) / 10000.0

    with rio.open(row.read(1)) as src:
        hr = src.read().astype(np.float32) / 10000.0

    np.save(lr_file, lr)
    np.save(hr_file, hr)

    if (n + 1) % 25 == 0:
        print(f"Cached {n + 1}/{len(train_indices)}")

# ============================================
# 3. Local
# ============================================

class LocalSen2VenusDataset(Dataset):

    def __init__(self, cache_dir, length):
        self.cache_dir = cache_dir
        self.length = length

    def __len__(self):
        return self.length

    def __getitem__(self, i):

        lr = np.load(f"{self.cache_dir}/{i}_lr.npy")
        hr = np.load(f"{self.cache_dir}/{i}_hr.npy")

        return (
            torch.from_numpy(lr),
            torch.from_numpy(hr)
        )

# ============================================
# 4. TRAINING SETUP
# ============================================

from torch.utils.data import random_split, DataLoader
cache_dir = "/content/sen2venus_cache"
train_indices = np.arange(1000)

# Use the cached dataset
full_dataset = LocalSen2VenusDataset(
    cache_dir,
    len(train_indices)
)

# 80% training / 20% validation
train_size = int(0.8 * len(full_dataset))
val_size = len(full_dataset) - train_size

train_set, val_set = random_split(
    full_dataset,
    [train_size, val_size],
    generator=torch.Generator().manual_seed(42)
)

train_loader = DataLoader(
    train_set,
    batch_size=16,
    shuffle=True,
    num_workers=0,
    pin_memory=True
)

val_loader = DataLoader(
    val_set,
    batch_size=16,
    shuffle=False,
    num_workers=0,
    pin_memory=True
)

print("Training samples:", len(train_set))
print("Validation samples:", len(val_set))
print("Training batches:", len(train_loader))
print("Validation batches:", len(val_loader))

"""### CNN + Transformer"""

# @title
# ============================================
# CNN + TRANSFORMER SUPER-RESOLUTION
# ============================================

import torch
import torch.nn as nn
import torch.nn.functional as F


class ResidualBlock(nn.Module):

    def __init__(self, channels):
        super().__init__()

        self.conv1 = nn.Conv2d(
            channels, channels, 3, padding=1
        )

        self.conv2 = nn.Conv2d(
            channels, channels, 3, padding=1
        )

        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):

        residual = self.relu(self.conv1(x))
        residual = self.conv2(residual)

        return x + residual


class ResidualGroup(nn.Module):

    def __init__(self, channels, num_blocks=4):
        super().__init__()

        self.blocks = nn.Sequential(
            *[
                ResidualBlock(channels)
                for _ in range(num_blocks)
            ]
        )

        self.conv = nn.Conv2d(
            channels, channels, 3, padding=1
        )

    def forward(self, x):

        residual = self.blocks(x)
        residual = self.conv(residual)

        return x + residual


class TransformerBlock(nn.Module):

    def __init__(
        self,
        channels,
        num_heads=8,
        window_size=8,
        shift_size=0,
        mlp_ratio=2
    ):
        super().__init__()

        self.window_size = window_size
        self.shift_size = shift_size

        self.norm1 = nn.LayerNorm(channels)

        self.attention = nn.MultiheadAttention(
            embed_dim=channels,
            num_heads=num_heads,
            batch_first=True
        )

        self.norm2 = nn.LayerNorm(channels)

        hidden = channels * mlp_ratio

        self.mlp = nn.Sequential(
            nn.Linear(channels, hidden),
            nn.GELU(),
            nn.Linear(hidden, channels)
        )

    def forward(self, x):

        B, C, H, W = x.shape
        ws = self.window_size
        ss = self.shift_size

        # ----------------------------------------
        # Shift feature map
        # ----------------------------------------

        if ss > 0:
            x = torch.roll(
                x,
                shifts=(-ss, -ss),
                dims=(2, 3)
            )

        # ----------------------------------------
        # Split into windows
        # ----------------------------------------

        x = x.view(
            B,
            C,
            H // ws,
            ws,
            W // ws,
            ws
        )

        x = x.permute(
            0, 2, 4, 3, 5, 1
        ).contiguous()

        # [B, number_of_windows, ws*ws, C]

        x = x.view(
            B,
            (H // ws) * (W // ws),
            ws * ws,
            C
        )

        # Merge windows into batch dimension

        x = x.view(
            -1,
            ws * ws,
            C
        )

        # ----------------------------------------
        # Self attention
        # ----------------------------------------

        residual = x

        x_norm = self.norm1(x)

        attention_out, _ = self.attention(
            x_norm,
            x_norm,
            x_norm
        )

        x = residual + attention_out

        # ----------------------------------------
        # MLP
        # ----------------------------------------

        residual = x

        x = residual + self.mlp(
            self.norm2(x)
        )

        # ----------------------------------------
        # Restore windows
        # ----------------------------------------

        x = x.view(
            B,
            H // ws,
            W // ws,
            ws,
            ws,
            C
        )

        x = x.permute(
            0, 5, 1, 3, 2, 4
        ).contiguous()

        x = x.view(
            B,
            C,
            H,
            W
        )

        # ----------------------------------------
        # Reverse shift
        # ----------------------------------------

        if ss > 0:
            x = torch.roll(
                x,
                shifts=(ss, ss),
                dims=(2, 3)
            )

        return x


class CNNTransformerSR(nn.Module):

    def __init__(
        self,
        in_channels=10,
        out_channels=8,
        features=96,
        num_groups=4,
        blocks_per_group=4,
        transformer_blocks=2
    ):
        super().__init__()

        # ========================================
        # CNN HEAD
        # ========================================

        self.head = nn.Conv2d(
            in_channels,
            features,
            3,
            padding=1
        )

        # ========================================
        # CNN FEATURE EXTRACTION
        # ========================================

        self.cnn_body = nn.Sequential(
            *[
                ResidualGroup(
                    features,
                    blocks_per_group
                )
                for _ in range(num_groups)
            ],

            nn.Conv2d(
                features,
                features,
                3,
                padding=1
            )
        )

        # ========================================
        # TRANSFORMER
        # ========================================

        self.transformer = nn.Sequential(
              TransformerBlock(
                  features,
                  num_heads=8,
                  window_size=8,
                  shift_size=0,
                  mlp_ratio=2
              ),

              TransformerBlock(
                  features,
                  num_heads=8,
                  window_size=8,
                  shift_size=4,
                  mlp_ratio=2
              )
          )

        # ========================================
        # FUSION
        # ========================================

        self.fusion = nn.Conv2d(
            features,
            features,
            3,
            padding=1
        )

        # ========================================
        # 2× UPSAMPLING
        # ========================================

        self.upsample = nn.Sequential(

            nn.Conv2d(
                features,
                features * 4,
                3,
                padding=1
            ),

            nn.PixelShuffle(2),

            nn.ReLU(inplace=True)
        )

        # ========================================
        # OUTPUT
        # ========================================

        self.tail = nn.Conv2d(
            features,
            out_channels,
            3,
            padding=1
        )

        # ========================================
        # BICUBIC SKIP
        # ========================================

        self.skip = nn.Conv2d(
            in_channels,
            out_channels,
            1
        )

    def forward(self, x):

        # CNN features
        features = self.head(x)

        cnn_features = self.cnn_body(features)

        features = features + cnn_features

        # Transformer global attention
        transformer_features = self.transformer(
            features
        )

        features = features + transformer_features

        # Fusion
        features = self.fusion(features)

        # Upsample
        features = self.upsample(features)

        # Predict HR spectral bands
        output = self.tail(features)

        # Bicubic baseline
        skip = self.skip(x)

        skip = F.interpolate(
            skip,
            scale_factor=2,
            mode="bicubic",
            align_corners=False
        )

        return output + skip

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model = CNNTransformerSR().to(device)

print("Device:", device)
print(
    "Parameters:",
    sum(p.numel() for p in model.parameters())
)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=5e-4
)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="min",
    factor=0.5,
    patience=3
)

class SpectralLoss(nn.Module):

    def __init__(
        self,
        mse_weight=1.0,
        spectral_weight=0.1,
        gradient_weight=0.05
    ):
        super().__init__()

        self.mse_weight = mse_weight
        self.spectral_weight = spectral_weight
        self.gradient_weight = gradient_weight

    def forward(self, prediction, target):

        # Pixel reconstruction
        mse = torch.mean(
            (prediction - target) ** 2
        )

        # Spectral consistency
        pred_mean = prediction.mean(
            dim=1, keepdim=True
        )

        target_mean = target.mean(
            dim=1, keepdim=True
        )

        pred_spectral = prediction - pred_mean
        target_spectral = target - target_mean

        spectral = torch.mean(
            (pred_spectral - target_spectral) ** 2
        )

        # Spatial gradients
        pred_dx = (
            prediction[:, :, :, 1:]
            - prediction[:, :, :, :-1]
        )

        target_dx = (
            target[:, :, :, 1:]
            - target[:, :, :, :-1]
        )

        pred_dy = (
            prediction[:, :, 1:, :]
            - prediction[:, :, :-1, :]
        )

        target_dy = (
            target[:, :, 1:, :]
            - target[:, :, :-1, :]
        )

        gradient = (
            torch.mean(torch.abs(pred_dx - target_dx))
            +
            torch.mean(torch.abs(pred_dy - target_dy))
        )

        return (
            self.mse_weight * mse
            + self.spectral_weight * spectral
            + self.gradient_weight * gradient
        )


criterion = SpectralLoss()

print("Loss:", criterion)

import time

epochs = 50

best_val_loss = float("inf")
best_epoch = 0

for epoch in range(epochs):

    # ==========================
    # TRAIN
    # ==========================

    model.train()

    train_loss = 0.0
    start = time.time()

    for batch_idx, (lr, hr) in enumerate(train_loader):

        lr = lr.to(device, non_blocking=True)
        hr = hr.to(device, non_blocking=True)

        optimizer.zero_grad()

        prediction = model(lr)

        loss = criterion(prediction, hr)

        loss.backward()
        optimizer.step()

        train_loss += loss.item()

        if (batch_idx + 1) % 25 == 0:
            print(
                f"Epoch {epoch+1}/{epochs} | "
                f"Batch {batch_idx+1}/{len(train_loader)} | "
                f"Loss: {loss.item():.6f}"
            )

    train_loss /= len(train_loader)

    # ==========================
    # VALIDATION
    # ==========================

    model.eval()

    val_loss = 0.0

    with torch.no_grad():

        for lr, hr in val_loader:

            lr = lr.to(device, non_blocking=True)
            hr = hr.to(device, non_blocking=True)

            prediction = model(lr)

            loss = criterion(prediction, hr)

            val_loss += loss.item()

    val_loss /= len(val_loader)

    # ==========================
    # LEARNING RATE SCHEDULER
    # ==========================

    scheduler.step(val_loss)

    print(
        "Learning rate:",
        optimizer.param_groups[0]["lr"]
    )

    elapsed = time.time() - start


    # ==========================
    # BEST CHECKPOINT
    # ==========================

    if val_loss < best_val_loss:

        best_val_loss = val_loss
        best_epoch = epoch + 1

        torch.save(
            model.state_dict(),
            "/content/best_sen2venus_sr_model_cnn_plus_transformer.pth"
        )

        status = " ⭐ NEW BEST"

    else:
        status = ""

    print(
        f"\nEpoch {epoch+1}/{epochs} COMPLETE | "
        f"Train Loss: {train_loss:.6f} | "
        f"Val Loss: {val_loss:.6f} | "
        f"Best: {best_val_loss:.6f} "
        f"(Epoch {best_epoch}) | "
        f"Time: {elapsed:.1f}s"
        f"{status}\n"
    )

# Load best model
model.load_state_dict(
    torch.load(
        "/content/best_sen2venus_sr_model_cnn_plus_transformer.pth",
        map_location=device
    )
)

model.eval()

print("=" * 60)
print("TRAINING FINISHED")
print(f"Best Epoch    : {best_epoch}")
print(f"Best Val Loss : {best_val_loss:.6f}")
print("Best model loaded.")
print("=" * 60)

import math

model.eval()

mse_total = 0.0
count = 0

with torch.no_grad():

    for lr, hr in val_loader:

        lr = lr.to(device)
        hr = hr.to(device)

        prediction = model(lr)

        mse = torch.mean(
            (prediction - hr) ** 2
        )

        mse_total += mse.item()
        count += 1

mse = mse_total / count

psnr = 10 * math.log10(1.0 / mse)

print(f"Validation MSE : {mse:.6f}")
print(f"Validation PSNR: {psnr:.2f} dB")

from scipy.ndimage import zoom
import matplotlib.pyplot as plt
import numpy as np

model.eval()

lr, hr = val_set[5]

with torch.no_grad():

    prediction = model(
        lr.unsqueeze(0).to(device)
    ).cpu().squeeze(0).numpy()

lr = lr.numpy()
hr = hr.numpy()

# Bicubic baseline
bicubic = np.stack([
    zoom(lr[i], 2, order=3)
    for i in range(10)
])

lr_rgb = lr[[0, 1, 2]].transpose(1, 2, 0)
bicubic_rgb = bicubic[[0, 1, 2]].transpose(1, 2, 0)
pred_rgb = prediction[[0, 1, 2]].transpose(1, 2, 0)
hr_rgb = hr[[0, 1, 2]].transpose(1, 2, 0)

fig, ax = plt.subplots(
    1, 4,
    figsize=(24, 6)
)

ax[0].imshow(np.clip(lr_rgb / 0.5, 0, 1))
ax[0].set_title("LR")

ax[1].imshow(np.clip(bicubic_rgb / 0.5, 0, 1))
ax[1].set_title("Bicubic 2×")

ax[2].imshow(np.clip(pred_rgb / 0.5, 0, 1))
ax[2].set_title("Improved CNN")

ax[3].imshow(np.clip(hr_rgb / 0.5, 0, 1))
ax[3].set_title("Ground Truth HR")

for a in ax:
    a.axis("off")

plt.tight_layout()
plt.show()

"""### Comparison"""

# ============================================================
# COMPARE CURRENT WINNER VS NEW CHECKPOINT
# ============================================================

import torch
import math

new_checkpoint = "/content/best_sen2venus_sr_model_cnn_plus_transformer_new.pth"

def evaluate_checkpoint(checkpoint_path):

    model.load_state_dict(
        torch.load(
            checkpoint_path,
            map_location=device
        )
    )

    model.eval()

    mse_total = 0.0
    count = 0

    with torch.no_grad():

        for lr, hr in val_loader:

            lr = lr.to(device)
            hr = hr.to(device)

            prediction = model(lr)

            mse = torch.mean(
                (prediction - hr) ** 2
            )

            mse_total += mse.item()
            count += 1

    mse = mse_total / count

    psnr = 10 * math.log10(
        1.0 / mse
    )

    return mse, psnr


# ============================================================
# CURRENT WINNER
# ============================================================

old_mse, old_psnr = evaluate_checkpoint(
    "/content/best_sen2venus_sr_model_cnn_plus_transformer.pth"
)

print("=" * 60)
print("CURRENT WINNER")
print("=" * 60)
print(f"Validation MSE : {old_mse:.6f}")
print(f"Validation PSNR: {old_psnr:.2f} dB")


# ============================================================
# NEW CHECKPOINT
# ============================================================

new_mse, new_psnr = evaluate_checkpoint(
    new_checkpoint
)

print()
print("=" * 60)
print("NEW CHECKPOINT")
print("=" * 60)
print(f"Validation MSE : {new_mse:.6f}")
print(f"Validation PSNR: {new_psnr:.2f} dB")


# ============================================================
# COMPARISON
# ============================================================

print()
print("=" * 60)
print("COMPARISON")
print("=" * 60)

print(f"Current winner : {old_psnr:.2f} dB")
print(f"New checkpoint : {new_psnr:.2f} dB")
print(f"Difference     : {new_psnr - old_psnr:+.2f} dB")

if new_psnr > old_psnr:
    print("\n🏆 NEW CHECKPOINT WINS!")

elif old_psnr > new_psnr:
    print("\n🏆 CURRENT WINNER REMAINS BEST!")

else:
    print("\n🤝 EXACTLY THE SAME PSNR")


# ============================================================
# LEAVE THE BETTER MODEL LOADED
# ============================================================

if new_psnr > old_psnr:

    model.load_state_dict(
        torch.load(
            new_checkpoint,
            map_location=device
        )
    )

    print("\nNew checkpoint loaded as the winner.")

else:

    model.load_state_dict(
        torch.load(
            "/content/best_sen2venus_sr_model_cnn_plus_transformer.pth",
            map_location=device
        )
    )

    print("\nCurrent winner loaded.")



"""### Adding GAN"""

import torch

CANDIDATE_PATH = "/content/best_sen2venus_sr_model_gan_finetuned.pth"  # <-- update to your actual uploaded filename

temp_model = CNNTransformerSR().to(device)
temp_model.load_state_dict(torch.load(CANDIDATE_PATH, map_location=device))
temp_model.eval()

val_loss = 0.0
with torch.no_grad():
    for lr_img, hr_img in val_loader:
        lr_img, hr_img = lr_img.to(device), hr_img.to(device)
        pred = temp_model(lr_img)
        val_loss += criterion(pred, hr_img).item()
val_loss /= len(val_loader)

print(f"Verified val loss of {CANDIDATE_PATH}: {val_loss:.6f}")

import shutil

VERIFIED_VAL_LOSS = val_loss  # uses the number just computed above

shutil.copy(CANDIDATE_PATH, GLOBAL_BEST_PATH)
with open(GLOBAL_BEST_META_PATH, "w") as f:
    f.write(str(VERIFIED_VAL_LOSS))

global_best_val_loss = VERIFIED_VAL_LOSS
print(f"Seeded GLOBAL BEST at {VERIFIED_VAL_LOSS:.6f}")

# ============================================
# 5.0 SAFE CHECKPOINT SETUP (run this before Stage 2)
# ============================================

import torch
import os
import time
import shutil

CHECKPOINT_DIR = "/content/drive/MyDrive/sen2venus_checkpoints"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# Unique ID per run — prevents any run from overwriting another run's file
RUN_ID = time.strftime("%Y%m%d_%H%M%S")
RUN_CHECKPOINT_PATH = f"{CHECKPOINT_DIR}/gan_run_{RUN_ID}.pth"

# This is the ONE file that represents your best result across ALL runs, ever.
GLOBAL_BEST_PATH = f"{CHECKPOINT_DIR}/GLOBAL_BEST.pth"
GLOBAL_BEST_META_PATH = f"{CHECKPOINT_DIR}/GLOBAL_BEST_meta.txt"

# --------------------------------------------
# Load current global-best val loss so new runs
# know what they actually need to beat (not "inf")
# --------------------------------------------

def load_global_best_val_loss():
    if os.path.exists(GLOBAL_BEST_META_PATH):
        with open(GLOBAL_BEST_META_PATH, "r") as f:
            return float(f.read().strip())
    return float("inf")

def save_global_best(model, val_loss, source_path):
    shutil.copy(source_path, GLOBAL_BEST_PATH)
    with open(GLOBAL_BEST_META_PATH, "w") as f:
        f.write(str(val_loss))
    print(f"[GLOBAL BEST UPDATED] New global best val loss: {val_loss:.6f} (saved to {GLOBAL_BEST_PATH})")

global_best_val_loss = load_global_best_val_loss()

print(f"[Checkpoint Setup] This run's checkpoint: {RUN_CHECKPOINT_PATH}")
print(f"[Checkpoint Setup] Current global best val loss to beat: {global_best_val_loss:.6f}")

# ============================================
# 5. GAN FINE-TUNING (STAGE 2) — IMPROVED VERSION
# ============================================

generator = model

generator.load_state_dict(torch.load(GLOBAL_BEST_PATH, map_location=device))
generator.to(device)
print(f"[Setup] Loaded generator from GLOBAL BEST ({global_best_val_loss:.6f}).")

# --------------------------------------------
# Discriminator (PatchGAN + spectral norm, feature-matching-ready)
# --------------------------------------------

class Discriminator(nn.Module):

    def __init__(self, in_channels=8, features=64):
        super().__init__()

        def block(in_c, out_c, stride):
            return [
                nn.utils.spectral_norm(                       # CHANGE 2: spectral norm
                    nn.Conv2d(in_c, out_c, 3, stride=stride, padding=1)
                ),
                nn.LeakyReLU(0.2, inplace=True)
                # NOTE: InstanceNorm2d removed — spectral norm replaces it
            ]

        self.model = nn.ModuleList([                          # ModuleList so we can walk layers for feature matching
            *block(in_channels, features, 1),
            *block(features, features, 2),
            *block(features, features * 2, 1),
            *block(features * 2, features * 2, 2),
            *block(features * 2, features * 4, 1),
            *block(features * 4, features * 4, 2),
            nn.utils.spectral_norm(
                nn.Conv2d(features * 4, 1, 3, padding=1)
            )  # patch logits
        ])

    def forward(self, x, return_features=False):               # CHANGE 4: feature matching support
        feats = []
        h = x
        for layer in self.model:
            h = layer(h)
            if return_features and isinstance(layer, nn.LeakyReLU):
                feats.append(h)
        return (h, feats) if return_features else h


discriminator = Discriminator(in_channels=8).to(device)

adv_criterion = nn.BCEWithLogitsLoss()
pixel_criterion = criterion

# CHANGE 3: TTUR — wider G/D LR gap
g_optimizer = torch.optim.Adam(generator.parameters(), lr=5e-5, betas=(0.9, 0.999))
d_optimizer = torch.optim.Adam(discriminator.parameters(), lr=2e-4, betas=(0.9, 0.999))

adv_weight = 0.0005   # CHANGE 3: smaller than your last two runs
fm_weight = 1.0        # CHANGE 4: feature-matching weight

print(f"[Setup] Generator LR: {g_optimizer.param_groups[0]['lr']} | "
      f"Discriminator LR: {d_optimizer.param_groups[0]['lr']} | "
      f"adv_weight: {adv_weight} | fm_weight: {fm_weight}")


# --------------------------------------------
# CHANGE 1: RaGAN loss helpers
# --------------------------------------------

def d_ragan_loss(real_logits, fake_logits):
    real_rel = real_logits - fake_logits.mean(0, keepdim=True)
    fake_rel = fake_logits - real_logits.mean(0, keepdim=True)
    return 0.5 * (
        adv_criterion(real_rel, torch.ones_like(real_rel)) +
        adv_criterion(fake_rel, torch.zeros_like(fake_rel))
    )

def g_ragan_loss(real_logits, fake_logits):
    real_rel = real_logits - fake_logits.mean(0, keepdim=True)
    fake_rel = fake_logits - real_logits.mean(0, keepdim=True)
    return 0.5 * (
        adv_criterion(real_rel, torch.zeros_like(real_rel)) +
        adv_criterion(fake_rel, torch.ones_like(fake_rel))
    )


gan_epochs = 20
best_this_run_val_loss = float("inf")
best_this_run_epoch = 0

# CHANGE 5: early stopping state
patience = 3
epochs_since_improvement = 0

for epoch in range(gan_epochs):

    generator.train()
    discriminator.train()
    g_loss_total = d_loss_total = pixel_loss_total = adv_loss_total = fm_loss_total = 0.0
    epoch_start = time.time()

    for batch_idx, (lr_img, hr_img) in enumerate(train_loader):
        lr_img = lr_img.to(device, non_blocking=True)
        hr_img = hr_img.to(device, non_blocking=True)

        # ---------------- Discriminator step ----------------
        d_optimizer.zero_grad()
        with torch.no_grad():
            fake_hr = generator(lr_img)
        real_logits = discriminator(hr_img)
        fake_logits = discriminator(fake_hr.detach())
        d_loss = d_ragan_loss(real_logits, fake_logits)        # CHANGE 1
        d_loss.backward()
        d_optimizer.step()

        # ---------------- Generator step ----------------
        g_optimizer.zero_grad()
        fake_hr = generator(lr_img)
        fake_logits, fake_feats = discriminator(fake_hr, return_features=True)   # CHANGE 4
        with torch.no_grad():
            real_logits_g, real_feats = discriminator(hr_img, return_features=True)  # CHANGE 4 (fixed reference)

        pixel_loss = pixel_criterion(fake_hr, hr_img)
        adv_loss = g_ragan_loss(real_logits_g, fake_logits)     # CHANGE 1
        fm_loss = sum(
            F.l1_loss(f, r) for f, r in zip(fake_feats, real_feats)
        ) / len(fake_feats)                                     # CHANGE 4

        g_loss = pixel_loss + adv_weight * adv_loss + fm_weight * fm_loss
        g_loss.backward()
        g_optimizer.step()

        g_loss_total += g_loss.item()
        d_loss_total += d_loss.item()
        pixel_loss_total += pixel_loss.item()
        adv_loss_total += adv_loss.item()
        fm_loss_total += fm_loss.item()

        if (batch_idx + 1) % 10 == 0:
            with torch.no_grad():
                real_conf = torch.sigmoid(real_logits).mean().item()
                fake_conf = torch.sigmoid(fake_logits).mean().item()
            print(f"  Epoch {epoch+1}/{gan_epochs} | Batch {batch_idx+1}/{len(train_loader)} | "
                  f"G: {g_loss.item():.6f} (pix {pixel_loss.item():.6f} + adv {adv_loss.item():.6f} + fm {fm_loss.item():.6f}) | "
                  f"D: {d_loss.item():.6f} | D(real): {real_conf:.3f} D(fake): {fake_conf:.3f}")

    g_loss_total /= len(train_loader)
    d_loss_total /= len(train_loader)
    pixel_loss_total /= len(train_loader)
    adv_loss_total /= len(train_loader)
    fm_loss_total /= len(train_loader)

    generator.eval()
    val_loss = 0.0
    with torch.no_grad():
        for lr_img, hr_img in val_loader:
            lr_img, hr_img = lr_img.to(device), hr_img.to(device)
            pred = generator(lr_img)
            val_loss += pixel_criterion(pred, hr_img).item()
    val_loss /= len(val_loader)
    epoch_time = time.time() - epoch_start

    if val_loss < best_this_run_val_loss:
        best_this_run_val_loss = val_loss
        best_this_run_epoch = epoch + 1
        torch.save(generator.state_dict(), RUN_CHECKPOINT_PATH)
        status = " ⭐ new best THIS RUN — saved"
        epochs_since_improvement = 0                            # CHANGE 5
    else:
        status = ""
        epochs_since_improvement += 1                            # CHANGE 5

    if val_loss < global_best_val_loss:
        global_best_val_loss = val_loss
        save_global_best(generator, val_loss, RUN_CHECKPOINT_PATH if os.path.exists(RUN_CHECKPOINT_PATH) else None)
        status += " 🌍 NEW GLOBAL BEST"

    print(f"\nEpoch {epoch+1}/{gan_epochs} COMPLETE | "
          f"Avg G: {g_loss_total:.6f} (pix {pixel_loss_total:.6f} + adv*{adv_weight} {adv_loss_total:.6f} + fm*{fm_weight} {fm_loss_total:.6f}) | "
          f"Avg D: {d_loss_total:.6f} | Val Pixel Loss: {val_loss:.6f} | "
          f"This-run best: {best_this_run_val_loss:.6f} (epoch {best_this_run_epoch}) | "
          f"Global best: {global_best_val_loss:.6f} | Time: {epoch_time:.1f}s{status}\n")

    if epochs_since_improvement >= patience:                     # CHANGE 5
        print(f"Early stopping: no improvement for {patience} epochs.")
        break

print("=" * 60)
print(f"RUN {RUN_ID} FINISHED")
print(f"This run's best: {best_this_run_val_loss:.6f} (epoch {best_this_run_epoch}) → saved at {RUN_CHECKPOINT_PATH}")
print(f"All-time global best: {global_best_val_loss:.6f} → saved at {GLOBAL_BEST_PATH}")
print("=" * 60)

import math
import time
import torch
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import zoom

# ============================================================
# 1. LOAD YOUR 5m MODEL
# ============================================================

gan_model = CNNTransformerSR().to(device)

gan_model.load_state_dict(
    torch.load(GLOBAL_BEST_PATH, map_location=device)
)

gan_model.eval()

print("Your 5m model loaded.")


# ============================================================
# 2. LOAD SEN2SRLite
# ============================================================
# If already loaded, this part can be skipped.

import mlstac

sen2sr_model = mlstac.load(
    "model/SEN2SRLite_RGBN"
).compiled_model(device=device)

sen2sr_model = sen2sr_model.to(device)
sen2sr_model.eval()

print("SEN2SRLite loaded.")


# ============================================================
# 3. GET SAME VALIDATION SAMPLE
# ============================================================

lr, hr = val_set[5]

# lr = 10m
# hr = 5m

lr_device = lr.unsqueeze(0).to(device)


# ============================================================
# 4. YOUR MODEL: 10m -> 5m
# ============================================================

with torch.no_grad():

    start = time.perf_counter()

    your_prediction = gan_model(lr_device)

    if device.type == "cuda":
        torch.cuda.synchronize()

    your_time = time.perf_counter() - start

your_prediction = (
    your_prediction
    .cpu()
    .squeeze(0)
    .numpy()
)


# ============================================================
# 5. YOUR MODEL -> 2.5m
# ============================================================
# Bicubic upscale your 5m output by 2x.
# This makes its final spatial resolution equal to SEN2SRLite.

your_prediction_25m = np.stack([
    zoom(your_prediction[i], 2, order=3)
    for i in range(your_prediction.shape[0])
])


# ============================================================
# 6. SEN2SRLite: 10m -> 2.5m
# ============================================================

with torch.no_grad():

    if device.type == "cuda":
        torch.cuda.synchronize()

    start = time.perf_counter()

    sen_prediction = sen2sr_model(
        lr_device
    )

    if device.type == "cuda":
        torch.cuda.synchronize()

    sen_time = time.perf_counter() - start

sen_prediction = (
    sen_prediction
    .cpu()
    .squeeze(0)
    .numpy()
)


# ============================================================
# 7. CONVERT INPUT / HR TO NUMPY
# ============================================================

lr = lr.numpy()
hr = hr.numpy()


# ============================================================
# 8. BICUBIC BASELINES
# ============================================================

# 10m -> 5m
bicubic_5m = np.stack([
    zoom(lr[i], 2, order=3)
    for i in range(lr.shape[0])
])

# 10m -> 2.5m directly
bicubic_25m = np.stack([
    zoom(lr[i], 4, order=3)
    for i in range(lr.shape[0])
])


# ============================================================
# 9. CALCULATE YOUR MODEL PSNR AT 5m
# ============================================================

mse_your_model = np.mean(
    (your_prediction - hr) ** 2
)

psnr_your_model = 10 * math.log10(
    1.0 / mse_your_model
)


# ============================================================
# 10. PRINT RESULTS
# ============================================================

print("\n" + "=" * 60)
print("COMPARISON")
print("=" * 60)

print(f"Your model:")
print(f"  Resolution : 5 m")
print(f"  MSE        : {mse_your_model:.6f}")
print(f"  PSNR       : {psnr_your_model:.2f} dB")
print(f"  Time       : {your_time:.3f} sec")

print("\nSEN2SRLite:")
print("  Resolution : 2.5 m")
print(f"  Time       : {sen_time:.3f} sec")

print("\nBicubic:")
print("  10m -> 5m")
print("  10m -> 2.5m")


# ============================================================
# 11. RGB VISUALIZATION
# ============================================================

# Assuming:
# channel 0 = Red
# channel 1 = Green
# channel 2 = Blue

lr_rgb = lr[[0, 1, 2]].transpose(1, 2, 0)

bicubic_5m_rgb = bicubic_5m[[0, 1, 2]].transpose(1, 2, 0)

your_rgb = your_prediction[[0, 1, 2]].transpose(1, 2, 0)

your_25m_rgb = your_prediction_25m[[0, 1, 2]].transpose(1, 2, 0)

sen_rgb = sen_prediction[[0, 1, 2]].transpose(1, 2, 0)

bicubic_25m_rgb = bicubic_25m[[0, 1, 2]].transpose(1, 2, 0)


# ============================================================
# 12. DISPLAY
# ============================================================

fig, ax = plt.subplots(
    2,
    3,
    figsize=(18, 12)
)

ax[0, 0].imshow(np.clip(lr_rgb / 0.5, 0, 1))
ax[0, 0].set_title("LR Sentinel-2 (10m)")

ax[0, 1].imshow(np.clip(bicubic_5m_rgb / 0.5, 0, 1))
ax[0, 1].set_title("Bicubic (5m)")

ax[0, 2].imshow(np.clip(your_rgb / 0.5, 0, 1))
ax[0, 2].set_title(
    f"Your CNN + Transformer (5m)\nPSNR: {psnr_your_model:.2f} dB"
)

ax[1, 0].imshow(np.clip(your_25m_rgb / 0.5, 0, 1))
ax[1, 0].set_title("Your Model + Bicubic (2.5m)")

ax[1, 1].imshow(np.clip(sen_rgb / 0.5, 0, 1))
ax[1, 1].set_title(
    f"SEN2SRLite (2.5m)\nTime: {sen_time:.2f}s"
)

ax[1, 2].imshow(np.clip(bicubic_25m_rgb / 0.5, 0, 1))
ax[1, 2].set_title("Bicubic (2.5m)")

for a in ax.flat:
    a.axis("off")

plt.tight_layout()
plt.show()

# ============================================================
# SEN2SRLite TEST
# Sentinel-2 10m -> 2.5m Super Resolution
# ============================================================

# 1. Install everything
!pip install -q sen2sr mlstac git+https://github.com/ESDS-Leipzig/cubo.git

# ============================================================
# 2. Imports
# ============================================================

import time
import torch
import mlstac
import cubo
import sen2sr
import matplotlib.pyplot as plt

# ============================================================
# COMPLETE 5m MODEL vs SEN2SRLite COMPARISON
# ============================================================

import os
import math
import time
import torch
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import zoom
import mlstac


# ============================================================
# SETTINGS
# ============================================================

# Your trained model checkpoint
# GLOBAL_BEST_PATH should already point to your .pth file
# Example:
# GLOBAL_BEST_PATH = "/content/best_model.pth"

print("=" * 70)
print("5m MODEL vs SEN2SRLite")
print("=" * 70)

print("Device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))


# ============================================================
# 1. LOAD YOUR 5m MODEL
# ============================================================

gan_model = CNNTransformerSR().to(device)

gan_model.load_state_dict(
    torch.load(
        GLOBAL_BEST_PATH,
        map_location=device
    )
)

gan_model.eval()

print("\nYour 5m model loaded.")


# ============================================================
# 2. DOWNLOAD SEN2SRLite RGBN MODEL
# ============================================================

MODEL_DIR = "/content/SEN2SRLite_RGBN"

os.makedirs(MODEL_DIR, exist_ok=True)

mlstac.download(
    file="https://huggingface.co/tacofoundation/sen2sr/resolve/main/SEN2SRLite/NonReference_RGBN_x4/mlm.json",
    output_dir=MODEL_DIR,
)

print("SEN2SRLite downloaded.")


# ============================================================
# 3. LOAD SEN2SRLite
# ============================================================

sen2sr_model = mlstac.load(
    MODEL_DIR
).compiled_model(
    device=device
)

sen2sr_model = sen2sr_model.to(device)
sen2sr_model.eval()

print("SEN2SRLite loaded.")


# ============================================================
# 4. GET THE SAME VALIDATION SAMPLE
# ============================================================

lr, hr = val_set[5]

print("\nDataset:")
print("LR shape:", tuple(lr.shape))
print("HR shape:", tuple(hr.shape))


# ============================================================
# EXPECTED 10-BAND ORDER:
#
# 0 = B02
# 1 = B03
# 2 = B04
# 3 = B05
# 4 = B06
# 5 = B07
# 6 = B08
# 7 = B8A
# 8 = B11
# 9 = B12
#
# SEN2SRLite RGBN requires:
# B04, B03, B02, B08
# ============================================================

# Extract RGB + NIR in SEN2SR's required order
sen_lr = lr[[2, 1, 0, 6]]


# ============================================================
# 5. PREPARE TENSORS
# ============================================================

lr_device = lr.unsqueeze(0).to(device)
sen_lr_device = sen_lr.unsqueeze(0).to(device)

lr_device = torch.nan_to_num(
    lr_device,
    nan=0.0,
    posinf=0.0,
    neginf=0.0
)

sen_lr_device = torch.nan_to_num(
    sen_lr_device,
    nan=0.0,
    posinf=0.0,
    neginf=0.0
)


# ============================================================
# 6. YOUR MODEL
# 10m -> 5m
# ============================================================

if device.type == "cuda":
    torch.cuda.synchronize()

start = time.perf_counter()

with torch.no_grad():
    your_prediction = gan_model(lr_device)

if device.type == "cuda":
    torch.cuda.synchronize()

your_time = time.perf_counter() - start

your_prediction = (
    your_prediction
    .cpu()
    .squeeze(0)
    .numpy()
)

print("\nYour model inference complete.")


# ============================================================
# 7. YOUR MODEL PSNR AT 5m
# ============================================================

hr_np = hr.numpy()

mse_your = np.mean(
    (your_prediction - hr_np) ** 2
)

psnr_your = 10 * math.log10(
    1.0 / mse_your
)


# ============================================================
# 8. YOUR 5m OUTPUT -> 2.5m
#
# This is ONLY for visual comparison with SEN2SRLite.
# ============================================================

your_prediction_25m = np.stack([
    zoom(
        your_prediction[i],
        2,
        order=3
    )
    for i in range(your_prediction.shape[0])
])


# ============================================================
# 9. SEN2SRLite
# 10m -> 2.5m
# ============================================================

if device.type == "cuda":
    torch.cuda.synchronize()

start = time.perf_counter()

with torch.no_grad():
    sen_prediction = sen2sr_model(
        sen_lr_device
    )

if device.type == "cuda":
    torch.cuda.synchronize()

sen_time = time.perf_counter() - start

sen_prediction = (
    sen_prediction
    .cpu()
    .squeeze(0)
    .numpy()
)

print("SEN2SRLite inference complete.")


# ============================================================
# 10. BICUBIC BASELINES
# ============================================================

lr_np = lr.numpy()

# 10m -> 5m
bicubic_5m = np.stack([
    zoom(
        lr_np[i],
        2,
        order=3
    )
    for i in range(lr_np.shape[0])
])

# 10m -> 2.5m
bicubic_25m = np.stack([
    zoom(
        lr_np[i],
        4,
        order=3
    )
    for i in range(lr_np.shape[0])
])


# ============================================================
# 11. RESULTS
# ============================================================

print("\n")
print("=" * 70)
print("RESULTS")
print("=" * 70)

print("\nYOUR MODEL")
print("-" * 40)
print("Input      : 10 m")
print("Output     : 5 m")
print(f"MSE        : {mse_your:.6f}")
print(f"PSNR       : {psnr_your:.2f} dB")
print(f"Time       : {your_time:.4f} seconds")

print("\nSEN2SRLite")
print("-" * 40)
print("Input      : 10 m")
print("Output     : 2.5 m")
print(f"Time       : {sen_time:.4f} seconds")

print("\nVISUAL COMPARISON")
print("-" * 40)
print("Your model  : 10m -> 5m -> 2.5m bicubic")
print("SEN2SRLite  : 10m -> 2.5m")


# ============================================================
# 12. RGB IMAGES
# ============================================================

# Your dataset RGB order:
# B02 = 0
# B03 = 1
# B04 = 2

lr_rgb = lr_np[[2, 1, 0]].transpose(1, 2, 0)

bicubic_5m_rgb = bicubic_5m[[2, 1, 0]].transpose(1, 2, 0)

your_rgb = your_prediction[[2, 1, 0]].transpose(1, 2, 0)

your_25m_rgb = your_prediction_25m[[2, 1, 0]].transpose(1, 2, 0)

# SEN2SRLite output is:
# B04, B03, B02, B08
#
# Therefore RGB = channels 0,1,2
sen_rgb = sen_prediction[[0, 1, 2]].transpose(1, 2, 0)

bicubic_25m_rgb = bicubic_25m[[2, 1, 0]].transpose(1, 2, 0)


# ============================================================
# 13. VISUALIZATION
# ============================================================

fig, ax = plt.subplots(
    2,
    3,
    figsize=(18, 12)
)


ax[0, 0].imshow(
    np.clip(lr_rgb / 0.5, 0, 1)
)
ax[0, 0].set_title(
    "Original Sentinel-2\n10 m"
)


ax[0, 1].imshow(
    np.clip(bicubic_5m_rgb / 0.5, 0, 1)
)
ax[0, 1].set_title(
    "Bicubic\n10 m → 5 m"
)


ax[0, 2].imshow(
    np.clip(your_rgb / 0.5, 0, 1)
)
ax[0, 2].set_title(
    f"Your CNN + Transformer\n10 m → 5 m\nPSNR: {psnr_your:.2f} dB"
)


ax[1, 0].imshow(
    np.clip(your_25m_rgb / 0.5, 0, 1)
)
ax[1, 0].set_title(
    "Your Model + Bicubic\n5 m → 2.5 m"
)


ax[1, 1].imshow(
    np.clip(sen_rgb / 0.5, 0, 1)
)
ax[1, 1].set_title(
    f"SEN2SRLite\n10 m → 2.5 m\n{sen_time:.3f} sec"
)


ax[1, 2].imshow(
    np.clip(bicubic_25m_rgb / 0.5, 0, 1)
)
ax[1, 2].set_title(
    "Bicubic\n10 m → 2.5 m"
)


for a in ax.flat:
    a.axis("off")


plt.tight_layout()
plt.show()


# ============================================================
# 14. SHAPES
# ============================================================

print("\n")
print("=" * 70)
print("OUTPUT SHAPES")
print("=" * 70)

print("LR                  :", lr_np.shape)
print("Your 5m prediction  :", your_prediction.shape)
print("Your 2.5m visual    :", your_prediction_25m.shape)
print("SEN2SRLite 2.5m     :", sen_prediction.shape)
print("HR                   :", hr_np.shape)

